package sdk

import (
	"fmt"
	"sort"
	"strings"
	"sync"
)

// registry holds module constructors registered at init time. Registration is
// compile-time via blank imports in cmd/argus (generated by go generate), so the
// in-tree fast path has no reflection and no runtime discovery.
var registry = struct {
	mu sync.RWMutex
	m  map[string]func() Module
}{m: map[string]func() Module{}}

// Register adds a module constructor to the compile-time registry.
//
// It panics on a duplicate name: two modules claiming the same name is a build
// error that must surface immediately, not a silent shadowing at runtime.
func Register(f func() Module) {
	if f == nil {
		panic("sdk.Register: nil constructor")
	}
	m := f()
	name := m.Manifest().Name
	if name == "" {
		panic("sdk.Register: module with empty name")
	}
	registry.mu.Lock()
	defer registry.mu.Unlock()
	if _, dup := registry.m[name]; dup {
		panic(fmt.Sprintf("sdk.Register: duplicate module name %q", name))
	}
	registry.m[name] = f
}

// New instantiates a registered module by name.
func New(name string) (Module, bool) {
	registry.mu.RLock()
	f, ok := registry.m[name]
	registry.mu.RUnlock()
	if !ok {
		return nil, false
	}
	return f(), true
}

// Registered lists the names of all registered modules, sorted.
func Registered() []string {
	registry.mu.RLock()
	defer registry.mu.RUnlock()
	out := make([]string, 0, len(registry.m))
	for n := range registry.m {
		out = append(out, n)
	}
	sort.Strings(out)
	return out
}

// RegisteredModules instantiates every registered module, sorted by name.
func RegisteredModules() []Module {
	names := Registered()
	out := make([]Module, 0, len(names))
	for _, n := range names {
		if m, ok := New(n); ok {
			out = append(out, m)
		}
	}
	return out
}

// ValidateManifest checks a manifest for the mistakes that silently degrade
// governance: an empty egress allow-list on a networked module, an undeclared
// secret use, or an unreasonable cost estimate. `argus modules doctor` runs this
// across every registered module.
func ValidateManifest(m Manifest) []string {
	var problems []string

	switch {
	case m.Name == "":
		problems = append(problems, "empty name")
	case m.Name != strings.ToLower(m.Name):
		problems = append(problems, fmt.Sprintf("name %q is not lowercase; module names are matched literally on the CLI", m.Name))
	}
	if m.Version == "" {
		problems = append(problems, "empty version")
	}
	if m.Category == "" {
		problems = append(problems, "empty category")
	}
	if len(m.Consumes) == 0 {
		problems = append(problems, "declares no Consumes; it will never be scheduled")
	}
	if len(m.EgressHosts) == 0 {
		problems = append(problems, "empty EgressHosts: only valid for a module that reads local files")
	}
	for _, h := range m.EgressHosts {
		if h == "" || strings.ContainsAny(h, " /") {
			problems = append(problems, fmt.Sprintf("malformed egress host %q", h))
		}
		if strings.HasPrefix(h, "*.") {
			continue
		}
		if strings.Contains(h, "://") {
			problems = append(problems, fmt.Sprintf("egress host %q must be a bare hostname, not a URL", h))
		}
	}
	if m.CostPerCall < 0 {
		problems = append(problems, fmt.Sprintf("negative CostPerCall %v", m.CostPerCall))
	}
	for _, c := range m.Consumes {
		if !ValidEntityType(string(c)) {
			problems = append(problems, fmt.Sprintf("unknown Consumes type %q", c))
		}
	}
	for _, p := range m.Produces {
		if !ValidEntityType(string(p)) {
			problems = append(problems, fmt.Sprintf("unknown Produces type %q", p))
		}
	}
	seenSecret := map[string]bool{}
	for _, s := range m.Secrets {
		if s.Name == "" {
			problems = append(problems, "secret with empty name")
			continue
		}
		if seenSecret[s.Name] {
			problems = append(problems, fmt.Sprintf("duplicate secret %q", s.Name))
		}
		seenSecret[s.Name] = true
	}
	if m.Mode == ModeActive && m.Sensitivity == SensLow && len(m.EgressHosts) == 0 {
		problems = append(problems, "active mode with no declared egress is incoherent")
	}
	return problems
}

// SelectModules returns the registered modules that consume at least one of the
// supplied entity types, preserving name order. This is how `argus scan` picks
// collectors when the operator does not name any.
func SelectModules(types []EntityType, exclude map[string]bool) []string {
	want := make(map[EntityType]bool, len(types))
	for _, t := range types {
		want[t] = true
	}
	var out []string
	for _, name := range Registered() {
		if exclude[name] {
			continue
		}
		m, ok := New(name)
		if !ok {
			continue
		}
		for _, c := range m.Manifest().Consumes {
			if want[c] {
				out = append(out, name)
				break
			}
		}
	}
	return out
}
