// Package main blank-imports every first-party module so the compile-time
// registry is populated. Generated by `go generate`; edit modules.go, not this.
package main

import (
	_ "github.com/WildanDeveloper/argus/modules/domain/dnsrecords"
)
